-- BANCO DE DADOS DO CONTROLE DE PRESENÇA
-- Rode este script no SQL Editor do Supabase.
-- Depois, importe os nomes do dados.json conforme o README.

create table if not exists public.pessoas (
  id bigint generated by default as identity primary key,
  nome text not null,
  dados jsonb not null default '{}'::jsonb,
  presente boolean not null default false,
  atualizado_em timestamptz not null default now()
);

alter table public.pessoas enable row level security;

drop policy if exists "leitura publica pessoas" on public.pessoas;
create policy "leitura publica pessoas"
on public.pessoas for select
to anon
using (true);

drop policy if exists "marcar presenca anon" on public.pessoas;
create policy "marcar presenca anon"
on public.pessoas for update
to anon
using (true)
with check (true);

grant select on public.pessoas to anon;
grant update (presente, atualizado_em) on public.pessoas to anon;

-- Realtime (opcional, para atualização instantânea entre aparelhos):
alter publication supabase_realtime add table public.pessoas;
